import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import {  AiFillLinkedin } from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark":""}>
      <Head>
        <title>Tameem Jahangir Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-10 md:px-20 lg:px-40 dark:bg-teal-900'>
        <section className='h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Developed by TJ</h1>
            <ul className='flrx items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" /></li>
              <li><a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="linkforlinkedin">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Tameem Jahangir</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>Computer Science student with a passion for software development.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillLinkedin />
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden'>
            <Image src={deved} fill alt="3d image of TJ"/>
          </div>
        </section>

        <section>
          <div className='text-center'>
            <h3 className='text-3xl py-1'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
              CV intro goes here.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} alt="Design 3d image."/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Hydrogen Life Cycle</h3>
              <p className='py-2'>
                Team Project description goes here
              </p>
              <h4 className='py-4 text-teal-600 '>Made using:</h4>
              <p className='text-gray-800 py-1'>Unity</p>

            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portofolio</h3>
          </div>
        </section>
      </main>
    </div>
  )
}
